### ISSUE TITLE
raw-h2: pool test / fixture fails

### ISSUE THREAD

**Issue by dimaqq** [HENNGE/aapns#24]
```py
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:1854:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <selectors.KqueueSelector object at 0x7fde205bddc0>, timeout = 0.6137869281683797

    def select(self, timeout=None):
        timeout = None if timeout is None else max(timeout, 0)
        max_ev = len(self._fd_to_key)
        ready = []
        try:
>           kev_list = self._selector.control(None, max_ev, timeout)
E           KeyboardInterrupt

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/selectors.py:558: KeyboardInterrupt
==================================== 13 deselected in 5.90 seconds =====================================
Task was destroyed but it is pending!
task: <Task pending name='bg-write' coro=<Connection.background_write() running at /Users/dima.tisnek/misc/aapns/src/aapns/connection.py:373> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fde18134550>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<test_termination() running at /Users/dima.tisnek/misc/aapns/tests/stress/test_pool.py:71> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fde18126070>()]>>
Exception ignored in: <coroutine object test_termination at 0x7fde1811de40>
Traceback (most recent call last):
  File "/Users/dima.tisnek/misc/aapns/tests/stress/test_pool.py", line 72, in test_termination
  File "/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/aapns-qVMfpW3G-py3.9/lib/python3.9/site-packages/_pytest/python_api.py", line 715, in __exit__
  File "/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/aapns-qVMfpW3G-py3.9/lib/python3.9/site-packages/_pytest/_code/code.py", line 405, in __init__
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by dimaqq** [comment]
As of d6e84a0

**Comment by dimaqq** [comment]
```
tests/stress/test_pool.py::test_termination ^CTask was destroyed but it is pending!
task: <Task pending name='bg-write' coro=<Connection.background_write() done, defined at /Users/dima.tisnek/misc/aapns/src/aapns/connection.py:358> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7ff1b84e8220>()]>>
```

**Comment by dimaqq** [comment]
Done in the branch.
